### ISSUE TITLE
assertion failed: stats.cpu_usage > 0.0

### ISSUE THREAD

**Issue by jiacai2050** [apache/incubator-horaedb#1447]
### Describe this problem

CI failed
```
---- tests::test_normal_case stdout ----
thread 'tests::test_normal_case' panicked at src/components/system_stats/src/lib.rs:132:9:
assertion failed: stats.cpu_usage > 0.0
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8550f15e148407159af401e02b1d9259762b3496/library/std/src/panicking.rs:617:5
   1: core::panicking::panic_fmt
             at /rustc/8550f15e148407159af401e02b1d9259762b3496/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/8550f15e148407159af401e02b1d9259762b3496/library/core/src/panicking.rs:117:5
   3: system_stats::tests::check_system_stats
             at ./src/lib.rs:132:9
   4: system_stats::tests::test_normal_case::{{closure}}
             at ./src/lib.rs:144:9
```

### Server version

https://github.com/apache/incubator-horaedb/actions/runs/7580286355/job/20645860686?pr=1446

### Steps to reproduce

Run CI

### Expected behavior

Pass CI

**Comment by ShiKaiWi** [comment]
I'll remove it.

**Comment by ShiKaiWi** [comment]
It seems fixed already.
